-- MySQL Script generated by MySQL Workbench
-- Tue Aug 17 13:35:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Inventarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Inventarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inventarios` DEFAULT CHARACTER SET utf8 ;
USE `Inventarios` ;

-- -----------------------------------------------------
-- Table `Inventarios`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Direccion` (
  `Pais` VARCHAR(45) NOT NULL,
  `Departamento/Ciudad` VARCHAR(45) NOT NULL,
  `Municipio/Aldea` VARCHAR(45) NOT NULL,
  `Zona` VARCHAR(5) NOT NULL,
  `Otra_Descripcion` VARCHAR(45) NOT NULL,
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre_C` VARCHAR(25) NOT NULL,
  `Apellido_C` VARCHAR(25) NOT NULL,
  `NIT` VARCHAR(8) NULL,
  `Telefono` VARCHAR(8) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `idDireccion` INT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `fk_Clientes_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Inventarios`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre_P` VARCHAR(25) NOT NULL,
  `Contacto` VARCHAR(20) NOT NULL,
  `idDireccion` INT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idProveedor`),
  INDEX `fk_Proveedor_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Inventarios`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Bodega` (
  `idBodega` INT NOT NULL AUTO_INCREMENT,
  `idProductos` INT NOT NULL,
  `Stock` INT NOT NULL,
  PRIMARY KEY (`idBodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Fecha_Ingreso` DATE NOT NULL,
  `idProveedor` INT NOT NULL,
  `idBodega` INT NOT NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `Productos_Proveedor_idx` (`idProveedor` ASC) VISIBLE,
  INDEX `fk_Productos_Bodega1_idx` (`idBodega` ASC) VISIBLE,
  CONSTRAINT `Productos_Proveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `Inventarios`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Productos_Bodega`
    FOREIGN KEY (`idBodega`)
    REFERENCES `Inventarios`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Fecha_Pedido` DATE NOT NULL,
  `idProducto` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Cantidad` FLOAT NOT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Emision` DATE NOT NULL,
  `idCliente` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Met_Pago` VARCHAR(15) NOT NULL,
  `Total_Pagar` INT NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `Factura_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `Factura_Pedido_idx` (`idPedido` ASC) VISIBLE,
  CONSTRAINT `Factura_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Inventarios`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Factura_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Inventarios`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventarios`.`Detalle_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventarios`.`Detalle_Pedido` (
  `idDetalle_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `idPedido` INT NOT NULL,
  `idProductos` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Pedido`),
  INDEX `Detalle_Pedido_idx` (`idPedido` ASC) VISIBLE,
  INDEX `Detalle_Producto_idx` (`idProductos` ASC) VISIBLE,
  CONSTRAINT `Detalle_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Inventarios`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Detalle_Producto`
    FOREIGN KEY (`idProductos`)
    REFERENCES `Inventarios`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;